"use client";

import { useEffect, useMemo, useState } from "react";
import { Bell, ChevronDown, CreditCard, Globe, Grid, Headphones, Home, Hourglass, Moon, PlusCircle, Send, Settings, Shield, Sliders, TrendingUp, Wallet, Zap } from "lucide-react";
import { applyForCard, getMyCards } from "./actions";

type CardItem = { id:string; last4:string; brand:string; type:string; status:string; spendingLimit:number; issuedAt?:string; createdAt?:string };
type CardsData = { balance:number; cards:CardItem[] };
const statusStyle:Record<string,string>={active:"bg-emerald-50 text-emerald-700",pending:"bg-amber-50 text-amber-700",frozen:"bg-sky-50 text-sky-700",revoked:"bg-rose-50 text-rose-700"};
const navItems=[{label:"Home",href:"/dashboard",icon:Home},{label:"Transfer",href:"/transfer",icon:Send},{label:"Deposit",href:"/dashboard",icon:PlusCircle},{label:"Activity",href:"/transactions",icon:TrendingUp},{label:"Cards",href:"/cards",icon:CreditCard},{label:"Settings",href:"/account",icon:Settings},{label:"Support",href:"/support",icon:Headphones},{label:"More",href:"/dashboard",icon:Grid}];
function Metric({icon:Icon,box,label,value}:{icon:any;box:string;label:string;value:string}){return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><div className={`flex h-12 w-12 items-center justify-center rounded-xl ${box}`}><Icon size={23}/></div><div><p className="text-[11px] font-semibold tracking-[.12em] text-slate-400">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></div></div></div>}
export default function Cards(){
 const [data,setData]=useState<CardsData>({balance:0,cards:[]}); const [loading,setLoading]=useState(true); const [applying,setApplying]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [dark,setDark]=useState(false);
 async function load(){const token=localStorage.getItem("crestline_token"); if(!token){setError("Please sign in again.");setLoading(false);return;} try{setData(await getMyCards(token));setError("")}catch(e:any){setError(e?.message||"Unable to load your cards.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function apply(){const token=localStorage.getItem("crestline_token");if(!token){setError("Please sign in again.");return;}setApplying(true);setError("");setMessage("");try{const r=await applyForCard(token,"virtual","visa");setMessage(r.message);await load()}catch(e:any){setError(e?.message||"Unable to submit application.")}finally{setApplying(false)}}
 const active=data.cards.filter(c=>c.status==="active").length; const pending=data.cards.filter(c=>c.status==="pending").length; const blocked=data.cards.some(c=>["pending","active","frozen"].includes(c.status));
 return <div className={dark?"min-h-screen bg-slate-950 pb-28 text-white":"min-h-screen bg-slate-50 pb-28 text-slate-900"}>
  <header className="mx-auto flex max-w-5xl items-center justify-between px-5 pb-5 pt-6 sm:px-8"><a href="/dashboard" className="flex items-center gap-3"><span className="relative flex h-11 w-11 items-center justify-center rounded-full bg-sky-500 text-white"><span className="absolute bottom-2 h-0 w-0 border-l-[11px] border-r-[11px] border-b-[15px] border-l-transparent border-r-transparent border-b-white"/><span className="absolute bottom-2 h-0.5 w-6 rounded bg-white"/></span><span className="text-lg font-bold">Crestline Capital</span></a><div className="flex gap-2"><button onClick={()=>setDark(v=>!v)} className="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-white"><Moon size={18}/></button><button className="relative flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-white"><Bell size={18}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-sky-500"/></button></div></header>
  <main className="mx-auto max-w-5xl px-5 sm:px-8">{message&&<div className="mb-4 rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}{error&&<div className="mb-4 rounded-2xl border border-rose-100 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
   <section className="grid gap-3 md:grid-cols-3"><Metric icon={CreditCard} box="bg-sky-500 text-white" label="ACTIVE CARDS" value={loading?"—":String(active)}/><Metric icon={Hourglass} box="bg-amber-500 text-white" label="PENDING APPLICATIONS" value={loading?"—":String(pending)}/><Metric icon={Wallet} box="bg-emerald-500 text-white" label="TOTAL BALANCE" value={loading?"—":`$${data.balance.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`}/></section>
   <section className="relative mt-5 overflow-hidden rounded-3xl bg-gradient-to-br from-sky-500 to-blue-600 p-6 shadow-lg sm:p-8"><div className="relative"><div className="flex justify-end"><button className="flex items-center gap-2 rounded-full bg-white px-3 py-2 text-xs font-bold text-slate-800">🇺🇸 EN <ChevronDown size={14}/></button></div><h1 className="mt-6 text-2xl font-bold text-white sm:text-3xl">Virtual Cards Made Easy</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/90 sm:text-base">Create virtual cards for secure online payments, subscription management, and more. Enhanced security and spending control.</p><div className="mt-6 grid grid-cols-2 gap-3">{[[Shield,"Secure","Protected payments"],[Globe,"Global","Worldwide acceptance"],[Sliders,"Control","Spending limits"],[Zap,"Instant","Quick issuance"]].map(([I,t,d])=>{const Icon=I as any;return <div key={String(t)} className="rounded-xl bg-white/10 p-3 backdrop-blur-sm"><Icon size={19} className="text-white"/><p className="mt-3 text-sm font-bold text-white">{String(t)}</p><p className="text-xs text-white/75">{String(d)}</p></div>})}</div><button disabled={applying||blocked} onClick={()=>void apply()} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-5 py-3.5 text-sm font-bold text-slate-900 disabled:opacity-60"> <PlusCircle size={18}/> {applying?"Submitting…":pending>0?"Application Pending":active>0?"Card Already Active":"Apply Now"}</button>{blocked&&<p className="mt-2 text-center text-xs text-white/75">You can apply again after the current card is no longer pending or active.</p>}</div></section>
   <section className="mt-6 space-y-3"><h2 className="text-lg font-bold">Your cards</h2>{loading?<div className="rounded-2xl bg-white p-6 text-sm text-slate-400 shadow-sm">Loading your cards…</div>:data.cards.length===0?<div className="rounded-2xl border border-dashed border-slate-200 bg-white p-8 text-center shadow-sm"><CreditCard className="mx-auto text-sky-500" size={34}/><p className="mt-3 font-semibold">No virtual cards yet</p><p className="mt-1 text-sm text-slate-500">Apply above to request your first virtual card.</p></div>:data.cards.map(c=><article key={c.id} className={`rounded-2xl border p-4 ${dark?"border-slate-800 bg-slate-900":"border-slate-100 bg-white shadow-sm"}`}><div className="flex items-center justify-between"><div><p className="font-semibold capitalize">{c.type} card · {c.brand.toUpperCase()}</p><p className="mt-1 font-mono text-sm text-slate-500">•••• •••• •••• {c.last4}</p></div><div className="text-right"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${statusStyle[c.status]||"bg-slate-100 text-slate-600"}`}>{c.status}</span><p className="mt-2 text-xs text-slate-500">Limit ${c.spendingLimit.toLocaleString("en-US",{minimumFractionDigits:2})}</p></div></div></article>)}</section>
  </main><nav className={`fixed bottom-4 left-4 right-4 z-50 mx-auto max-w-5xl rounded-full border p-2 shadow-xl ${dark?"border-slate-700 bg-slate-900":"border-slate-100 bg-white"}`}><div className="flex items-center gap-1 overflow-x-auto">{navItems.map(({label,href,icon:Icon})=><a key={label} href={href} className={`flex min-w-[58px] shrink-0 flex-1 flex-col items-center justify-center gap-1 rounded-full px-2 py-2 text-[10px] font-semibold sm:flex-row sm:text-xs ${label==="Cards"?"bg-sky-500 text-white":dark?"text-slate-400":"text-slate-500"}`}><Icon size={17}/><span>{label}</span></a>)}</div></nav>
 </div>
}
