"use client";
import { useMemo, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import BankingShell from "@/components/BankingShell";

export default function AdminCardsPage(){
 const cardsQuery=useQuery(api.cards.adminList); const cards=useMemo(()=>cardsQuery??[],[cardsQuery]); const setStatus=useMutation(api.cards.setStatus); const [query,setQuery]=useState(""); const [status,setFilter]=useState("all");
 const filtered=useMemo(()=>cards.filter(c=>{const h=`${c.user?.name||""} ${c.user?.email||""} ${c.last4}`.toLowerCase();return(!query||h.includes(query.toLowerCase()))&&(status==='all'||c.status===status)}),[cards,query,status]);
 return <BankingShell admin><div className="min-h-screen bg-slate-950 px-5 py-8 text-slate-100"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-sky-400">Money / Cards</p><h1 className="mt-2 text-3xl font-bold">Cards Management</h1><p className="mt-2 text-sm text-slate-400">Convex is the only source of truth for card state.</p><div className="mt-6 grid gap-3 sm:grid-cols-4">{['pending','active','frozen','revoked'].map(s=><div key={s} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><small className="uppercase text-slate-500">{s}</small><b className="mt-2 block text-2xl">{cards.filter(c=>c.status===s).length}</b></div>)}</div><div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex gap-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customer, email or last 4" className="flex-1 rounded-xl border border-slate-700 bg-slate-950 px-4 py-2"/><select value={status} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-2"><option value="all">All</option><option value="pending">Pending</option><option value="active">Active</option><option value="frozen">Frozen</option><option value="revoked">Revoked</option></select></div><div className="mt-4 space-y-2">{filtered.map(card=><div key={card._id} className="flex flex-col gap-3 rounded-xl border border-slate-800 p-4 md:flex-row md:items-center md:justify-between"><div><b>{card.user?.name||'Unknown customer'}</b><p className="text-xs text-slate-500">{card.user?.email} · •••• {card.last4} · {card.type} {card.brand}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-800 px-3 py-1 text-xs">{card.status}</span>{card.status==='pending'&&<button onClick={()=>setStatus({cardId:card._id,status:'active'})} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold">Approve</button>}{card.status==='active'&&<button onClick={()=>setStatus({cardId:card._id,status:'frozen'})} className="rounded-lg bg-amber-600 px-3 py-2 text-xs font-semibold">Freeze</button>}{card.status==='frozen'&&<button onClick={()=>setStatus({cardId:card._id,status:'active'})} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold">Unfreeze</button>}{card.status!=='revoked'&&<button onClick={()=>setStatus({cardId:card._id,status:'revoked'})} className="rounded-lg bg-rose-600 px-3 py-2 text-xs font-semibold">Revoke</button>}</div></div>)}{cards.length===0&&<p className="p-8 text-center text-slate-500">No cards found.</p>}</div></div></div></div></BankingShell>;
}
