"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import BankingShell from "@/components/BankingShell";

export default function UserDetailPage(){
 const {id}=useParams<{id:string}>(); const userId=id as any; const data=useQuery(api.admin.getUser,{userId}); const freeze=useMutation(api.admin.setFrozen);
 if(data===undefined)return <BankingShell admin><div className="p-8 text-slate-400">Loading customer…</div></BankingShell>;
 if(!data)return null;
 const {user,transactions}=data;
 return <BankingShell admin><div className="min-h-screen bg-slate-50 p-5 text-slate-950"><div className="mx-auto max-w-6xl"><Link href="/admin/users" className="text-sm font-semibold text-blue-700">← Users</Link><div className="mt-4 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-bold">{user.name}</h1><p className="text-sm text-slate-500">{user.email} · {user.accountNumber}</p></div><button onClick={()=>freeze({userId,frozen:!user.isFrozen})} className={`rounded-xl px-4 py-2.5 text-sm font-semibold text-white ${user.isFrozen?'bg-emerald-600':'bg-rose-600'}`}>{user.isFrozen?'Unfreeze account':'Freeze account'}</button></div><div className="mt-6 grid gap-5 md:grid-cols-3"><section className="rounded-2xl bg-white p-5 shadow-sm md:col-span-2"><small className="uppercase tracking-wider text-slate-400">Available balance</small><div className="mt-2 text-4xl font-bold">${Number(user.balance).toLocaleString("en-US",{minimumFractionDigits:2})} {user.currency}</div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><small>Role</small><b className="block mt-1">{user.role}</b></div><div className="rounded-xl bg-slate-50 p-3"><small>Status</small><b className="block mt-1">{user.isFrozen?'Frozen':'Active'}</b></div><div className="rounded-xl bg-slate-50 p-3"><small>Joined</small><b className="block mt-1">{new Date(user.createdAt).toLocaleDateString()}</b></div></div></section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold">Account controls</h2><p className="mt-2 text-sm text-slate-500">All customer state is now stored and authorized in Convex.</p><div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">Account: {user.accountNumber}</div></section></div><section className="mt-5 rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold">Recent ledger activity</h2><div className="mt-4 divide-y divide-slate-100">{transactions.map(t=><div key={t._id} className="flex items-center justify-between py-3"><div><b>{t.description||t.type}</b><small className="block text-xs text-slate-500">{t.reference} · {new Date(t.createdAt).toLocaleString()}</small></div><strong>{t.amount.toFixed(2)} {t.currency}</strong></div>)}{!transactions.length&&<p className="py-8 text-center text-sm text-slate-500">No transactions.</p>}</div></section></div></div></BankingShell>;
}
