"use client";

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { api } from '@/lib/api';

type User = { id:string; name:string; email:string; accountNumber:string; balance:number; status:string; accountState:string; kycStatus:string; emailVerified:boolean; twoFactorEnabled:boolean; forcePinCheck:boolean; isFrozen:boolean; createdAt?:string; lastLoginAt?:string; restrictedMessages?:{inactive?:string;onHold?:string;suspended?:string;blocked?:string} };
type Tx = { _id:string; reference:string; description?:string; amount:any; direction?:string; status:string; createdAt?:string; occurredAt?:string; displayOnly?:boolean; affectsBalance?:boolean };
type Login = {when:string;ip:string;userAgent:string};
const money=(n:number)=>`$${n.toLocaleString('en-US',{minimumFractionDigits:4,maximumFractionDigits:4})}`;
const dec=(v:any)=>Number(v?.$numberDecimal ?? v ?? 0);
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
const card='rounded-2xl border border-slate-200 bg-white p-5 shadow-sm';

export default function UserDetailPage(){
 const {id}=useParams<{id:string}>(); const [user,setUser]=useState<User|null>(null); const [tx,setTx]=useState<Tx[]>([]); const [logs,setLogs]=useState<Login[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 const [balance,setBalance]=useState({amount:'',note:''}); const [manual,setManual]=useState({direction:'credit',amount:'',label:'',occurredAt:'',affectsBalance:true}); const [messages,setMessages]=useState({inactive:'',onHold:'',suspended:'',blocked:''});
 const load=()=>api.get(`/admin/users/${id}`).then(r=>{setUser(r.data.user);setTx(r.data.transactions||[]);setLogs(r.data.loginActivity||[]);setMessages({inactive:r.data.user.restrictedMessages?.inactive||'',onHold:r.data.user.restrictedMessages?.onHold||'',suspended:r.data.user.restrictedMessages?.suspended||'',blocked:r.data.user.restrictedMessages?.blocked||''});}).catch(e=>setError(e?.response?.data?.message||'Unable to load customer')).finally(()=>setLoading(false));
 useEffect(()=>{void load();},[id]);
 const update=async(payload:any)=>{setSaving(true);setError('');setMessage('');try{const r=await api.patch(`/admin/users/${id}`,payload);setUser(r.data.user);setMessage('Account settings saved.');}catch(e:any){setError(e?.response?.data?.message||'Unable to save settings')}finally{setSaving(false)}};
 const action=async(payload:any)=>{setSaving(true);setError('');setMessage('');try{const r=await api.post(`/admin/users/${id}`,payload);if(r.data.balance!==undefined)setUser(u=>u?{...u,balance:r.data.balance}:u);setMessage(r.data.message||'Action completed.');await load();}catch(e:any){setError(e?.response?.data?.message||'Action failed')}finally{setSaving(false)}};
 if(loading)return <div className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-7xl animate-pulse rounded-2xl bg-white p-10">Loading customer profile…</div></div>;
 if(!user)return <div className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-7xl rounded-2xl bg-white p-10 text-red-700">{error||'Customer not found'}</div></div>;
 return <div className="min-h-screen bg-slate-50 p-4 text-slate-950 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl">
  <div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><Link href="/admin/users" className="text-sm font-semibold text-blue-700">← Users</Link><h1 className="mt-2 text-3xl font-bold">{user.name}</h1><p className="text-sm text-slate-500">{user.email} · {user.accountNumber}</p></div><div className="flex gap-2"><span className="rounded-full bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">Admin control</span><button disabled={saving} onClick={()=>action({action:'rotate-account'})} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold">Rotate account</button></div></div>
  {message&&<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}{error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="grid gap-5 lg:grid-cols-3">
   <section className={`${card} lg:col-span-2`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Current balance</p><p className="mt-2 text-4xl font-bold tracking-tight">{money(user.balance)}</p></div><div className="text-right text-xs text-slate-500">Joined {user.createdAt?new Date(user.createdAt).toLocaleString():'—'}<br/>Last login {user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString():'Not recorded'}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><label className="text-xs font-semibold text-slate-500">Status<select value={user.status} onChange={e=>update({status:e.target.value})} className={`${input} mt-1`}><option value="active">Active</option><option value="suspended">Suspended</option><option value="closed">Closed</option></select></label><label className="text-xs font-semibold text-slate-500">Account state<select value={user.accountState} onChange={e=>update({accountState:e.target.value})} className={`${input} mt-1`}><option value="active">Active</option><option value="inactive">Inactive</option><option value="on-hold">On-hold</option><option value="suspended">Suspended</option></select></label><label className="text-xs font-semibold text-slate-500">KYC status<select value={user.kycStatus} onChange={e=>update({kycStatus:e.target.value})} className={`${input} mt-1`}><option value="unverified">Unverified</option><option value="pending">Pending</option><option value="verified">Verified</option><option value="rejected">Rejected</option></select></label></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3 text-sm"><span className="text-slate-500">Email</span><strong className="block mt-1">{user.emailVerified?'Verified':'Not verified'}</strong></div><div className="rounded-xl bg-slate-50 p-3 text-sm"><span className="text-slate-500">2FA</span><strong className="block mt-1">{user.twoFactorEnabled?'Enabled':'Off'}</strong></div><div className="rounded-xl bg-slate-50 p-3 text-sm"><span className="text-slate-500">Access</span><strong className="block mt-1">{user.isFrozen?'Blocked':'Available'}</strong></div></div></section>
   <section className={card}><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Security</p><h2 className="mt-1 text-lg font-bold">Access controls</h2><label className="mt-5 flex items-center gap-3 text-sm"><input type="checkbox" checked={user.forcePinCheck} onChange={e=>update({forcePinCheck:e.target.checked})}/> Force PIN check</label><button disabled={saving} onClick={()=>action({action:'reset-pin'})} className="mt-4 w-full rounded-xl border border-amber-200 bg-amber-50 px-4 py-2.5 text-sm font-semibold text-amber-800">Reset / clear transaction PIN</button></section>
   <section className={`${card} lg:col-span-2`}><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Balance adjustment</p><h2 className="mt-1 text-lg font-bold">Manual credit or debit</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input inputMode="decimal" value={balance.amount} onChange={e=>setBalance({...balance,amount:e.target.value})} placeholder="Amount" className={input}/><input value={balance.note} onChange={e=>setBalance({...balance,note:e.target.value})} placeholder="Note (optional)" className={input}/></div><div className="mt-3 flex gap-2"><button disabled={saving||!balance.amount} onClick={()=>action({action:'balance',direction:'credit',amount:Number(balance.amount),note:balance.note})} className="rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white">Credit</button><button disabled={saving||!balance.amount} onClick={()=>action({action:'balance',direction:'debit',amount:Number(balance.amount),note:balance.note})} className="rounded-xl bg-red-600 px-5 py-2.5 text-sm font-semibold text-white">Debit</button></div></section>
   <section className={card}><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Account notices</p><h2 className="mt-1 text-lg font-bold">Restricted-state messages</h2>{[['inactive','Inactive'],['onHold','On hold'],['suspended','Suspended'],['blocked','Blocked']].map(([k,label])=><label key={k} className="mt-3 block text-xs font-semibold text-slate-500">{label}<input value={(messages as any)[k]} onChange={e=>setMessages({...messages,[k]:e.target.value})} className={`${input} mt-1`} placeholder={`Notice shown for ${label.toLowerCase()}`}/></label>)}<button disabled={saving} onClick={()=>update({restrictedMessages:messages})} className="mt-4 w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Save messages</button></section>
   <section className={`${card} lg:col-span-2`}><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Add a transaction</p><h2 className="mt-1 text-lg font-bold">Manual ledger entry</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={manual.direction} onChange={e=>setManual({...manual,direction:e.target.value})} className={input}><option value="credit">Credit</option><option value="debit">Debit</option></select><input inputMode="decimal" value={manual.amount} onChange={e=>setManual({...manual,amount:e.target.value})} placeholder="Amount (USD)" className={input}/><input value={manual.label} onChange={e=>setManual({...manual,label:e.target.value})} placeholder="Label e.g. Salary deposit" className={input}/><input type="datetime-local" value={manual.occurredAt} onChange={e=>setManual({...manual,occurredAt:e.target.value})} className={input}/></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={manual.affectsBalance} onChange={e=>setManual({...manual,affectsBalance:e.target.checked})}/> Affect balance</label><button disabled={saving||!manual.amount||!manual.label} onClick={()=>action({action:'transaction',...manual,amount:Number(manual.amount)})} className="mt-4 rounded-xl bg-blue-700 px-5 py-2.5 text-sm font-semibold text-white">Add transaction</button></section>
  </div>
  <section className={`${card} mt-5`}><div className="mb-4"><h2 className="text-lg font-bold">Ledger & activity history</h2><p className="text-sm text-slate-500">Recent balance activity and display-only history.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">When</th><th className="px-4 py-3">Activity</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{tx.map(t=><tr key={t._id}><td className="px-4 py-3 text-slate-500">{new Date(t.occurredAt||t.createdAt||Date.now()).toLocaleString()}</td><td className="px-4 py-3 font-semibold">{t.description||t.reference}{t.displayOnly&&!t.affectsBalance&&<span className="ml-2 rounded-full bg-slate-100 px-2 py-1 text-[10px] text-slate-500">DISPLAY ONLY</span>}</td><td className={`px-4 py-3 font-semibold ${t.direction==='credit'?'text-emerald-700':'text-red-700'}`}>{t.direction==='credit'?'+':'−'}{money(dec(t.amount))}</td><td className="px-4 py-3 text-slate-500">{t.status}</td></tr>)}</tbody></table>{!tx.length&&<p className="p-8 text-center text-sm text-slate-500">No ledger activity.</p>}</div></section>
  <section className={`${card} mt-5`}><h2 className="text-lg font-bold">Login activity</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">When</th><th className="px-4 py-3">IP address</th><th className="px-4 py-3">User agent</th></tr></thead><tbody className="divide-y divide-slate-100">{logs.map((l,i)=><tr key={i}><td className="px-4 py-3">{new Date(l.when).toLocaleString()}</td><td className="px-4 py-3">{l.ip}</td><td className="px-4 py-3 text-slate-500">{l.userAgent}</td></tr>)}</tbody></table>{!logs.length&&<p className="p-8 text-center text-sm text-slate-500">No login activity recorded.</p>}</div></section>
 </div></div>;
}