"use client";

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';

type Customer = { id: string; name: string; email: string; accountNumber: string; status?: string; kycStatus?: string; emailVerified?: boolean; twoFactorEnabled?: boolean; createdAt?: string; isFrozen?: boolean };
const date = (v?: string) => v ? new Date(v).toLocaleDateString() : '—';
const pill = (value: string, tone: 'green'|'red'|'amber'|'slate' = 'slate') => `inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tone === 'green' ? 'bg-emerald-50 text-emerald-700' : tone === 'red' ? 'bg-red-50 text-red-700' : tone === 'amber' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600'}`;

export default function AdminUsersPage() {
  const [users, setUsers] = useState<Customer[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { api.get('/admin/users').then(r => setUsers(r.data.users)).catch(e => setError(e?.response?.data?.message || 'Unable to load users')).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => { const q = query.toLowerCase().trim(); return q ? users.filter(u => `${u.name} ${u.email} ${u.accountNumber}`.toLowerCase().includes(q)) : users; }, [users, query]);
  return <div className="min-h-screen bg-slate-50 p-4 text-slate-950 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl">
    <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">People</p><h1 className="mt-2 text-3xl font-bold">Users</h1><p className="mt-1 text-sm text-slate-500">Search, review and manage every customer account.</p></div><Link href="/admin" className="w-fit rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">← Overview</Link></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Customer accounts</h2><p className="text-sm text-slate-500">{users.length} records</p></div><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name, email or account number" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-2.5 text-sm outline-none focus:border-blue-500 sm:w-80" /></div>
      {error && <div className="m-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
      <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">#</th><th className="px-5 py-3">User</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">KYC</th><th className="px-5 py-3">Email verified</th><th className="px-5 py-3">2FA</th><th className="px-5 py-3">Joined</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? Array.from({length:7}).map((_,i)=><tr key={i}><td colSpan={8} className="px-5 py-4"><div className="h-5 animate-pulse rounded bg-slate-100"/></td></tr>) : filtered.map((u,i)=><tr key={u.id} className="hover:bg-slate-50"><td className="px-5 py-4 text-slate-400">{i+1}</td><td className="px-5 py-4"><div className="font-semibold">{u.name}</div><div className="text-xs text-slate-500">{u.email}<br/>{u.accountNumber}</div></td><td className="px-5 py-4"><span className={pill(u.isFrozen || u.status === 'suspended' ? 'Blocked':'Active', u.isFrozen || u.status === 'suspended' ? 'red':'green')}>{u.isFrozen || u.status === 'suspended' ? 'Blocked':'Active'}</span></td><td className="px-5 py-4"><span className={pill(u.kycStatus || 'pending', u.kycStatus === 'verified' ? 'green' : u.kycStatus === 'rejected' ? 'red':'amber')}>{u.kycStatus || 'pending'}</span></td><td className="px-5 py-4">{u.emailVerified ? <span className="text-emerald-700">Verified</span> : <span className="text-amber-700">Pending</span>}</td><td className="px-5 py-4">{u.twoFactorEnabled ? 'Enabled' : 'Off'}</td><td className="px-5 py-4 text-slate-500">{date(u.createdAt)}</td><td className="px-5 py-4 text-right"><Link href={`/admin/users/${u.id}`} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Manage</Link></td></tr>)}</tbody></table></div>
      {!loading && filtered.length === 0 && <div className="p-12 text-center text-sm text-slate-500">No customers match your search.</div>}
    </div></div></div>;
}