"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";

type Customer = { _id: string; name: string; email: string; accountNumber: string; isFrozen: boolean; createdAt: number };
const date=(v:number)=>new Date(v).toLocaleDateString();
export default function AdminUsersPage(){
 const users=useQuery(api.adminUsers.list); const [query,setQuery]=useState("");
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim(); return q?(users||[]).filter(u=>`${u.name} ${u.email} ${u.accountNumber}`.toLowerCase().includes(q)):users||[]},[users,query]);
 return <div className="min-h-screen bg-slate-50 p-4 text-slate-950 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">People</p><h1 className="mt-2 text-3xl font-bold">Users</h1><p className="mt-1 text-sm text-slate-500">Search, review and manage every customer account.</p></div><Link href="/admin" className="w-fit rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">← Overview</Link></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Customer accounts</h2><p className="text-sm text-slate-500">{users?.length??0} records</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email or account number" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-2.5 text-sm outline-none focus:border-blue-500 sm:w-80"/></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">#</th><th className="px-5 py-3">User</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Joined</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{users===undefined?Array.from({length:7}).map((_,i)=><tr key={i}><td colSpan={5} className="px-5 py-4"><div className="h-5 animate-pulse rounded bg-slate-100"/></td></tr>):filtered.map((u,i)=><tr key={u._id} className="hover:bg-slate-50"><td className="px-5 py-4 text-slate-400">{i+1}</td><td className="px-5 py-4"><div className="font-semibold">{u.name}</div><div className="text-xs text-slate-500">{u.email}<br/>{u.accountNumber}</div></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${u.isFrozen?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{u.isFrozen?'Blocked':'Active'}</span></td><td className="px-5 py-4 text-slate-500">{date(u.createdAt)}</td><td className="px-5 py-4 text-right"><Link href={`/admin/users/${u._id}`} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Manage</Link></td></tr>)}</tbody></table>{users!==undefined&&filtered.length===0&&<div className="p-12 text-center text-sm text-slate-500">No customers match your search.</div>}</div></div></div></div>;
}
