"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { useMutation } from "convex/react";
import { api } from "@/convex/_generated/api";
import { authClient } from "@/lib/auth-client";

export default function AdminSetupPage(){
 const ensureProfile=useMutation(api.users.ensureProfile); const promote=useMutation(api.admin.promoteFirstAdmin); const [name,setName]=useState("Crestline Administrator"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [pin,setPin]=useState(""); const [secret,setSecret]=useState(""); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");setMessage("");try{const signup=await authClient.signUp.email({name,email,password});if(signup.error)throw new Error(signup.error.message||"Unable to create administrator account");await ensureProfile({name,email,pin});const result=await promote({email:email.toLowerCase(),secret});setMessage(`Administrator created successfully. Account number: ${result.accountNumber}`);}catch(err:any){setError(err?.message||"Unable to create administrator");}finally{setLoading(false)}}
 return <main className="auth-page"><div className="auth-card glass" style={{maxWidth:620}}><Link className="brand" href="/"><span className="brand-mark">C</span><span>Crestline <b>Capital</b></span></Link><span className="eyebrow">ONE-TIME CONVEX ADMIN SETUP</span><h1>Create administrator</h1><p>Register the administrator through Better Auth, create the Convex profile, then promote that account. This can only succeed when no administrator exists.</p>{message&&<div className="form-success">{message}</div>}{error&&<div className="form-error">{error}</div>} {!message&&<form onSubmit={submit}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required/></label><label>Transaction PIN<input inputMode="numeric" pattern="[0-9]{4,6}" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))} minLength={4} maxLength={6} required/></label><label>Convex bootstrap secret<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} minLength={16} required/></label><button className="dashboard-primary full" disabled={loading}>{loading?"Creating administrator…":"Create administrator →"}</button></form>}<div className="auth-footer"><Link href="/login">Return to secure login</Link></div></div></main>;
}
