"use client";
import { useState } from "react";
import Link from "next/link";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { authClient } from "@/lib/auth-client";

export default function SettingsPage(){
 const session=authClient.useSession(); const user=useQuery(api.users.me,session.data?{}:"skip"); const [dark,setDark]=useState(false); const [saved,setSaved]=useState(false);
 if(session.isPending||user===undefined)return <main className="premium-loading">Loading…</main>; if(!session.data||!user)return null;
 return <main className={dark?'min-h-screen bg-slate-950 pb-28 text-white':'min-h-screen bg-slate-50 pb-28 text-slate-900'}><header className="border-b border-slate-100 bg-white px-5 py-4"><div className="mx-auto flex max-w-2xl items-center justify-between"><Link href="/dashboard" className="font-bold">Crestline Capital</Link><button onClick={()=>setDark(!dark)} className="rounded-full bg-slate-100 p-2">{dark?'☀':'◐'}</button></div></header><section className="mx-auto max-w-2xl px-5 py-7"><p className="text-xs font-bold tracking-[.18em] text-sky-500">ACCOUNT SETTINGS</p><h1 className="mt-1 text-3xl font-bold">Settings</h1><div className="mt-6 space-y-4"><Panel title="Profile"><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name" value={user.name}/><Field label="Email" value={user.email}/><Field label="Account number" value={user.accountNumber}/><Field label="Role" value={user.role}/></div></Panel><Panel title="Security"><div className="rounded-2xl bg-slate-50 p-4 text-sm">Authentication is managed by Better Auth and sessions are backed by Convex.</div><Link href="/account" className="mt-4 inline-block rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold">Manage account security</Link></Panel><Panel title="Preferences"><label className="text-sm font-semibold">Theme<select value={dark?'dark':'light'} onChange={e=>setDark(e.target.value==='dark')} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 font-normal"><option value="light">Light</option><option value="dark">Dark</option></select></label><button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),2000)}} className="mt-4 rounded-2xl bg-sky-500 px-6 py-3 font-semibold text-white">Save preferences</button>{saved&&<span className="ml-3 text-sm text-emerald-600">Saved</span>}</Panel></div></section></main>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-bold">{title}</h2>{children}</section>}
function Field({label,value}:{label:string;value:string}){return <label className="text-xs font-semibold text-slate-500">{label}<input value={value} readOnly className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700 outline-none"/></label>}
