"use client";
import Link from "next/link";
import { useMemo, useState } from "react";

type AdminUser={id:string;name:string;email:string;accountNumber:string;balance:number;isFrozen:boolean;status?:string;kycStatus?:'unverified'|'verified'|'pending'|'rejected';createdAt?:string};
const formatDate=(value?:string)=>value?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(value)):'—';
export default function UsersTable({users,onUpdated,onToggleFreeze}:{users:AdminUser[];onUpdated:(users:AdminUser[])=>void;onToggleFreeze:(id:string,frozen:boolean)=>Promise<void>}){
 const [query,setQuery]=useState('');const [busyId,setBusyId]=useState<string|null>(null);const filtered=useMemo(()=>{const v=query.trim().toLowerCase();return v?users.filter(u=>`${u.name} ${u.email} ${u.accountNumber}`.toLowerCase().includes(v)):users},[query,users]);
 async function toggleFreeze(u:AdminUser){setBusyId(u.id);try{await onToggleFreeze(u.id,!u.isFrozen);onUpdated(users.map(x=>x.id===u.id?{...x,isFrozen:!u.isFrozen}:x));}finally{setBusyId(null)}}
 return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold text-slate-950">Recent users</h2><p className="mt-1 text-sm text-slate-500">Customer accounts and access controls.</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email or account" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-blue-500 sm:w-72"/></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">#</th><th className="px-5 py-3">User</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Joined</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((u,i)=><tr key={u.id} className="hover:bg-slate-50"><td className="px-5 py-4 text-slate-400">{i+1}</td><td className="px-5 py-4"><div className="font-semibold">{u.name}</div><div className="text-xs text-slate-500">{u.email} · {u.accountNumber}</div></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${u.isFrozen?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{u.isFrozen?'Blocked':'Active'}</span></td><td className="px-5 py-4 text-slate-600">{formatDate(u.createdAt)}</td><td className="px-5 py-4 text-right"><div className="flex justify-end gap-2"><Link href={`/admin/users/${u.id}`} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Manage</Link><button disabled={busyId===u.id} onClick={()=>toggleFreeze(u)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700">{u.isFrozen?'Unblock':'Block'}</button></div></td></tr>)}</tbody></table>{filtered.length===0&&<div className="p-10 text-center text-sm text-slate-500">No users match your search.</div>}</div></section>;
}
